### ISSUE TITLE
Feature request: widen the basic trace for visibility

### ISSUE THREAD

**Issue by basil96** [alsolera/VideoF2B#82]
When videos are recorded against a bright background (into the sun), the existing 1-pixel wide trace has a tendency to blend into the background as the figure progresses, making it difficult to see.  The same occurs when capturing screenshots of video for demonstration/training purposes.  At the end of a figure, the start of the trace is light green/yellow.

I propose tracing with a width of 2 pixels from now on.  I tried 3 pixels, but that's too coarse.
This may be an issue for videos with lower than 1080p resolution (1px width is already a lot for 720p).  If that's a concern, I may add logic for adaptive scaling.

**Comment by basil96** [comment]
As an example, existing trace looks like this:
![image](https://github.com/alsolera/VideoF2B/assets/13767466/faca878d-45a5-4912-a0f5-80c62d293823)

The proposed trace would look like this:
![image](https://github.com/alsolera/VideoF2B/assets/13767466/f1bafb40-24d5-4abb-b7e2-74c3c1f266b0)

**Comment by alsolera** [comment]
Thank you @basil96 
I agree that it is needed for HD videos, but I usually use lower resolution videos. I think it should be based on the image size.
Maybe a simple "if img.shape > 720"?

**Comment by basil96** [comment]
Improved. See new push in the PR.
